Unit Liesconf;

interface

uses Dialogs, Basic, Globvar, Standard, Messages, SysUtils,
     Texte, Graphics;

procedure Liesconfig;

implementation

procedure  Liesconfig;
var
  Datei        : textfile;
  Ctext        : string;
  Xconf        : string[20];
  LinienTypS   : string;
  KonfidenzS   : string[3];
  StufeS       : string[3];
  Co           : integer;
  LaengeS      : string[6];
  SigmaS       : string[6];
  KanteS       : string[6];
  WinkelS      : string[6];
  FarbeS       : string;
  i            : byte;
  BBreiteS     : string;
begin
  DecimalSeparator := '.';
  assignFile(Datei,FabricS+'\'+'Fabric.ini');
  try
    reset (Datei);
  except
    on EInOutError do
    begin
      Beep;
      ShowMessage (Tx(1));  { Datei Fabric.ini nicht gefunden}
    end;
  end;
  for i := 1 to 4 do Grau[i] := false;
  readln (Datei,Ctext); Xconf := Nachkomma(Ctext);   {1}
  Texttest (Ctext,1);
  readln (Datei,Ctext);                              {2}
  Texttest (Ctext,2); {Grafik}
  readln (Datei,Ctext);FarbeS := Nachkomma(Ctext);   {3}
  Texttest (Ctext,3);
  HintFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);FarbeS := Nachkomma(Ctext);   {4}
  Texttest (Ctext,4);
  RahmenFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);FarbeS := Nachkomma(Ctext);   {5}
  Texttest (Ctext,5);
  UmfangFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);FarbeS := Nachkomma(Ctext);   {6}
  Texttest (Ctext,6);
  DiagrFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);FarbeS := Nachkomma(Ctext);   {7}
  Texttest (Ctext,7);
  DatenFarbe := StringToColor(FarbeS);
  readln (Datei, Ctext);FarbeS := Nachkomma(Ctext);   {8}
  Texttest (Ctext, 8);
  GrosskreisFarbe := StringToColor(FarbeS);;
  readln (Datei,Ctext);DatenSymbol := Nachkomma (Ctext); {9}
  Texttest (Ctext,9);
  readln (Datei, Ctext);LinientypS := Nachkomma (Ctext); {10}
  Texttest (Ctext, 10);
  PsLinien (LinienTypS, LinienTyp);
  readln (Datei, Ctext);FarbeS := Nachkomma (Ctext);     {11}
  Texttest (Ctext, 11);
  RoseFarbe := StringToColor(FarbeS);;
  readln (Datei,Ctext);FarbeS := Nachkomma (Ctext); {12}
  KleinFarbe := StringToColor(FarbeS);
  Texttest (Ctext,12);
  readln (Datei,Ctext); Xconf := Nachkomma(Ctext); {Suchpfad} {13}
  Texttest (Ctext,13);
  readln (Datei, PfadS);                                 {14}
  Kompress (PfadS);
  if (RightS (PfadS, 1) <> ':') and (RightS(PfadS, 1) <> '\')
     then PfadS := PfadS + '\';
  readln (Datei,GrafikS);                                {15}
  Kompress (GrafikS);
  if (RightS (GrafikS, 1) <> ':') and (RightS (GrafikS, 1) <> '\')
  then GrafikS := GrafikS + '\';
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); ObenUntenS := Xconf; {16}
  Texttest (Ctext,16);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); PasswortS := Xconf; {17}
  Texttest (Ctext,17);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); SpracheS := XConf;  {18}
  Texttest (Ctext,18);
  readln (Datei,Ctext);
  Texttest (Ctext, 19); {Statistics}
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); KonfidenzS := XConf;
  Texttest (Ctext, 20);
  val (KonfidenzS, Konfidenz, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 21);
  EigenFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 22);
  OeffnungFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 23);
  VertrauFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); ProjektionS := XConf;
  Texttest (Ctext, 24);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 25);
  NetzFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 26);
  AequatorFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 27);
  RGFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 28);
  KoordinFarbe := StringToColor (FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 29);
  Isolinie[1] := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 30);
  Isolinie[2] := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 31);
  Isolinie[3] := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 32);
  Isolinie[4] := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 33);
  Isolinie[5] := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 34);
  ObSlipLine := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 35);
  UnSlipLine := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 36);
  PfeilFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 37);
  TheorFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LinientypS := XConf;
  Texttest (Ctext, 38);
  PsLinien (LinienTypS, IsoTyp[1]);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LinientypS := XConf;
  Texttest (Ctext, 39);
  PsLinien (LinienTypS, IsoTyp[2]);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LinientypS := XConf;
  Texttest (Ctext, 40);
  PsLinien (LinienTypS, IsoTyp[3]);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LinientypS := XConf;
  Texttest (Ctext, 41);
  PsLinien (LinienTypS, IsoTyp[4]);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LinientypS := XConf;
  Texttest (Ctext, 42);
  PsLinien (LinienTypS, IsoTyp[5]);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); VielfacheS := XConf;
  Texttest (Ctext, 43);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); StufeS := XConf;
  Texttest (Ctext, 44);
  IsoStufe[1] := StrtoInt(StufeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); StufeS := XConf;
  Texttest (Ctext, 45);
  IsoStufe[2] := StrtoInt(StufeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); StufeS := XConf;
  Texttest (Ctext, 46);
  IsoStufe[3] := StrtoInt(StufeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); StufeS := XConf;
  Texttest (Ctext, 47);
  IsoStufe[4] := StrtoInt(StufeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); StufeS := XConf;
  Texttest (Ctext, 48);
  IsoStufe[5] := StrtoInt(StufeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); StufeS := XConf;
  Texttest (Ctext, 49);
  Kalotte := StrtoInt(StufeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); StufeS := XConf;
  Texttest (Ctext, 50);
  val (StufeS, Vielfach, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 51);
  OberOeffnungFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 52);
  OberVertrauFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); GeraetS := XConf;
  Texttest (Ctext, 53);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 56);
  PeriFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LaengeS := XConf;
  Texttest (Ctext, 57);
  val(LaengeS, HpRadius, Co);
  HpRadius := HpRadius/10;
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LaengeS := XConf;
  Texttest (Ctext, 58);
  val(LaengeS, XKoord, Co);
  XKoord := XKoord/10;
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LaengeS := XConf;
  Texttest (Ctext, 59);
  val(LaengeS, YKoord, Co);
  YKoord := YKoord/10;
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); RoseS := XConf;
  Texttest (Ctext, 60);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LaengeS := XConf;
  Texttest (Ctext, 61);
  val(LaengeS, Intervall, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LaengeS := XConf;
  Texttest (Ctext, 62);
  val(LaengeS, Inkrement, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); SigmaS := XConf;
  Texttest (Ctext, 63);
  val(SigmaS, ASigma1, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); SigmaS := XConf;
  Texttest (Ctext, 64);
  val(SigmaS, FSigma1, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); SigmaS := XConf;
  Texttest (Ctext, 65);
  val(SigmaS, ASigma3, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); SigmaS := XConf;
  Texttest (Ctext, 66);
  val(SigmaS, FSigma3, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); KanteS := XConf;
  Texttest (Ctext, 67);
  val(KanteS, Kante, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); KanteS := XConf;
  Texttest (Ctext, 68);
  val(KanteS, XAnfang, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); KanteS := XConf;
  Texttest (Ctext, 69);
  val(KanteS, YAnfang, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); WinkelS := XConf;
  Texttest (Ctext, 70);
  val(WinkelS,Abstand, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); WinkelS := XConf;
  Texttest (Ctext, 71);
  val(WinkelS,NetzInkrement, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); WinkelS := XConf;
  Texttest (Ctext, 72);
  val(WinkelS,Kippen, Co);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 73);
  GrundFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LaengeS := XConf;
  Texttest (Ctext, 74);
  val(LaengeS, DruckenR, Co);
  DruckenR := DruckenR/10;
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LaengeS := XConf;
  Texttest (Ctext, 75);
  val(LaengeS, DruckenX, Co);
  DruckenX := DruckenX/10;
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); LaengeS := XConf;
  Texttest (Ctext, 76);
  val(LaengeS, DruckenY, Co);
  DruckenY := DruckenY/10;
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 77);
  ObjektFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  Texttest (Ctext, 78);
  ScherFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  TextTest (Ctext, 79);
  KompressionFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := XConf;
  TextTest (Ctext, 80);
  DehnungFarbe := StringToColor(FarbeS);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); SymbolKompression := XConf;
  TextTest (Ctext, 81);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); SymbolDehnung := XConf;
  TextTest (Ctext, 82);
  readln (Datei,Ctext);Xconf := Nachkomma(Ctext); FarbeS := Xconf;
  TextTest (Ctext, 83);
  FarbePoly := StringToColor(FarbeS);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  TextTest (Ctext, 84);
  MaxDaten := StrtoInt (Xconf);
  readln (Datei, CText); Xconf := Nachkomma(Ctext);
  TextTest (CText, 85);
  Faktor := StrToFloat(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  TextTest (Ctext, 86);
  val (Xconf, YDruckFaktor, Co);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  TextTest (Ctext, 87);
  val (Xconf, Glaettung, Co);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  TextTest (Ctext, 88);
  DarstellungS := Xconf;
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext,89);
  val (Xconf, FryFaktor, Co);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext,90);
  FryFarbeEllipse := StringToColor(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext,91);
  FryFarbePunkte := StringToColor(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext,92);
  FryFarbeFlaeche := StringToColor(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 93);
  SigmaFarbe := StringToColor(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 94);
  KlickFarbe := StringToColor (Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 95);
  FourierFarbe := StringToColor (XConf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 96);
  LiesHinweisS := Xconf;
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 97);
  FuellFarbe := StringToColor (Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 98);
  IsogonFarbe := StringToColor (Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 99);
  Strich := StrtoInt (Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 100);
  StrichI[1] := StrToInt(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 101);
  StrichI[2] := StrToInt(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 102);
  StrichI[3] := StrToInt(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 103);
  StrichI[4] := StrToInt(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 104);
  StrichI[5] := StrToInt(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 105);
  GAbstand := StrToInt(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest (Ctext, 106);
  LinearFarbe := StringToColor (Xconf);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  SLaenge := StrToInt(Xconf);
  Texttest (Ctext, 107);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  Prozent := StrToInt (Xconf);
  Texttest (Ctext, 108);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  HarmFarbe := StringToColor (Xconf);;
  Texttest (Ctext, 109);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  VekFarbe := StringToColor (Xconf);;
  Texttest (Ctext, 110);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  ChiHintFarbe := StringToColor (Xconf);;
  Texttest (Ctext, 111);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  ChiKoorFarbe := StringToColor (Xconf);;
  Texttest (Ctext, 112);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  ChiGraphFarbe := StringToColor (Xconf);;
  Texttest (Ctext, 113);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  FEllipseStilS := Xconf;
  Texttest (Ctext, 114);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS := Xconf;
  BBreiteF := StrToInt(BBreiteS);
  Texttest (Ctext, 115);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS := Xconf;
  BBreiteD := StrToInt(BBreiteS);
  Texttest (Ctext, 116);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS := Xconf;
  BBreiteMa := StrToInt(BBreiteS);
  Texttest (Ctext, 117);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS  := Xconf;
  BBreiteSt := StrToInt(BBreiteS);
  Texttest (Ctext, 118);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS := Xconf;
  BBreiteFou := StrToInt(BBreiteS);
  Texttest (Ctext, 119);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS := Xconf;
  BBreiteM := StrToInt(BBreiteS);
  Texttest (Ctext, 120);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS := Xconf;
  BBreiteT := StrToInt(BBreiteS);
  Texttest (Ctext, 121);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS  := Xconf;
  BBreiteSh := StrToInt(BBreiteS);
  Texttest (Ctext, 122);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS  := Xconf;
  BBreiteP  := StrToInt(BBreiteS);
  Texttest (Ctext, 123);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS  := Xconf;
  BBreiteI  := StrToInt(BBreiteS);
  Texttest (Ctext, 124);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS  := Xconf;
  BBreiteCh := StrToInt(BBreiteS);
  Texttest (Ctext, 125);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  Texttest(Ctext,126);
  NNFarbeEllipse := StringToColor(Xconf);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  NNFarbeFlaeche := StringToColor(Xconf);
  Texttest(Ctext,127);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  NEllipseStilS := Xconf;
  Texttest (Ctext, 128);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS  := Xconf;
  BBreiteFl := StrToInt(BBreiteS);
  Texttest (Ctext, 129);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS  := Xconf;
  BBreiteHs := StrToInt(BBreiteS);
  Texttest (Ctext, 130);
  readln (Datei,Ctext); Xconf := Nachkomma(Ctext);
  IterFarbe := StringToColor(Xconf);
  Texttest(Ctext, 131);
  readln (Datei,Ctext); Xconf := Nachkomma(Ctext);
  DSchrift := Xconf;
  Texttest(Ctext, 132);
  readln (Datei,Ctext); Xconf := Nachkomma(Ctext);
  DGroesse := StrToInt(Xconf);
  Texttest(Ctext, 133);
  readln (Datei,Ctext); Xconf := Nachkomma(Ctext);
  DFarbe := StringToColor(Xconf);
  Texttest(Ctext, 134);
  readln (Datei,Ctext); Xconf := Nachkomma(Ctext);
  DStyle := TFontStyles(TFontStyle(StrToInt(Xconf)));
  Texttest(Ctext, 135);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  MVektorFarbe := StringToColor(Xconf);
  TextTest(Ctext,136);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  MHintFarbe := StringToColor(Xconf);
  TextTest(Ctext,137);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  MRahmenFarbe := StringToColor(Xconf);
  TextTest(Ctext,138);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  MKoordinFarbe := StringToColor(Xconf);
  TextTest(Ctext,139);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  MS1FuellFarbe := StringToColor(Xconf);
  TextTest(Ctext,140);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  MS2FuellFarbe := StringToColor(Xconf);
  TextTest(Ctext,141);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  MS3FuellFarbe := StringToColor(Xconf);
  TextTest(Ctext,142);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  HHintFarbe := StringToColor(Xconf);
  TextTest(Ctext,143);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  HRahmenFarbe := StringToColor(Xconf);
  TextTest(Ctext,144);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  HKoordinFarbe := StringToColor(Xconf);
  TextTest(Ctext,145);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  HFuellFarbe := StringToColor(Xconf);
  TextTest(Ctext,146);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS  := Xconf;
  BBreiteMo := StrToInt(BBreiteS);
  Texttest (Ctext, 147);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  BBreiteS  := Xconf;
  BBreiteHi := StrToInt(BBreiteS);
  Texttest (Ctext, 148);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  TopDiag := StrToInt(Xconf);
  TextTest (Ctext, 149);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  LeftDiag := StrToInt(Xconf);
  TextTest (Ctext, 150);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  ULap := StrToInt(Xconf);
  TextTest (Ctext, 151);
  readln (Datei, Ctext); Xconf := NachKomma(Ctext);
  SymbolRadii := Xconf;
  TextTest (Ctext, 152);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  BBreiteS := Xconf;
  BBreiteW := StrToInt(BBreiteS);
  Texttest (Ctext, 153);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  BLaenge := StrToInt(Xconf);
  Texttest (Ctext, 154);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  BOben := StrToInt(Xconf);
  Texttest (Ctext, 155);
  readln (Datei, Ctext); Xconf := Nachkomma(Ctext);
  BLinks := StrToInt(Xconf);
  Texttest (Ctext, 156);
  closeFile (Datei);
  Konfig;
end;
end.