unit Globvar;

interface
uses Graphics;

const
  DemoZeit   = 30;
  DemoB      = false;
  ConfigEnde = 113;

type
  TFWord    = array[0..5000] of word;
  TFShort   = array[0..5000] of shortint;
  Tww       = array of array of real;
  TFByte    = array[0..5000] of byte;
  TFReal    = array[0..5000] of real;
  TFBoolean = array[0..5000] of boolean;

var
  Abbrechen         : boolean;
  Abstand           : integer;
  AequatorFarbe     : TColor;
  AJahr             : word;
  AMonat            : byte;
  ASigma1           : word;
  Asigma3           : word;
  ATag              : byte;
  Ausb              : boolean;
  AziFeld           : array of word;
  BaudS             : string;
  B1Fou, B3Fou      : array of real;
  B5Fou             : array of real;
  Berechnung        : byte;
  BereichS          : string[10];
  Bo                : real;
  Breite            : word;
  DarstellungS      : string[10];
  DateiNameS        : array[0..100] of string;
  DateiZahl         : word;
  DatenFarbe        : TColor;
  Datensymbol       : string[15];
  DehnungFarbe      : TColor;
  DiagrFarbe        : TColor;
  DirectS           : string;
  DruckenR          : real;
  DruckenX          : real;
  DruckenY          : real;
  Dxfp,Dxfpud       : byte;
  EigenFarbe        : TColor;
  EingabeS          : string[30];
  EllipsoidS        : string[8];
  Faktor            : real;
  FalFeld           : array of word;
  Farbe             : TColor;
  FarbePoly         : TColor;
  FarbIso           : array[0..5] of byte;
  Fluss             : string;
  FormatS           : string[12];
  FSigma1           : shortint;
  FSigma3           : shortint;
  Gefuegetyp        : byte;
  GeraetS           : string[10];
  GrafikS           : string;
  GroesseS          : string[6];
  GrosskreisFarbe   : TColor;
  GrundFarbe        : TColor;
  HintFarbe         : TColor;
  Hoehe             : word;
  Horizontal        : word;
  HpRadius          : real;
  Inkrement         : byte;
  Intervall         : byte;
  Isolinie          : array [0..5] of TColor;
  IsoTyp            : array [0..5] of TPenStyle;
  IsoStufe          : array [0..5] of word;
  Kalotte           : word;
  Kante             : real;
  KeinPort          : boolean;
  KippWinkel        : integer;
  Kom               : byte;
  KomS              : array[0..20] of string;
  KompressionFarbe  : TColor;
  KonfigZeileS      : array[0..150] of string;
  Konfidenz         : byte;
  KoordinFarbe      : TColor;
  Lambda1           : array of word;
  Lambda2           : array of word;
  Lambda3           : array of word;
  Laufw2S           : string[3];
  Linientyp         : TPenStyle;
  manuell           : boolean;
  Matrix            : array[0..3, 0..3] of real;
  MaxDaten          : word;
  NameLiz           : string[80];
  NetzFarbe         : TColor;
  NetzInkrement     : integer;
  Oben              : word;
  OberOeffnungFarbe : TColor;
  OberVertrauFarbe  : TColor;
  ObjektFarbe       : TColor;
  ObSlipLine        : TColor;
  OeffnungFarbe     : TColor;
  PassS             : string[8];
  PasswortS         : string[8];
  PDatei            : TextFile;
  PeriFarbe         : TColor;
  PfadS             : string;
  PfeilFarbe        : TColor;
  PlatteS           : string[3];
  PlotRadius        : real;
  PlotZeile         : TextFile;
  ProjektionS       : string;
  PudS              : string[5];
  Programm          : byte;
  PwS               : string[6];
  Q                 : array[0..3, 0..3] of real;
  Radius            : word;
  RahmenFarbe       : TColor;
  Regelung          : array of byte;
  ReihenB           : byte;
  RekSimS           : string[4];
  RGFarbe           : TColor;
  RichtungenS       : string[20];
  RoseFarbe         : TColor;
  SAzifeld          : array of word;
  ScherFarbe        : TColor;
  Schlafe           : word;
  Schluessel        : integer;
  SchnittS          : string;
  Schrift           : byte;
  SchutzS           : string;
  SFalFeld          : array of shortint;
  SpracheS          : string[10];
  StextS            : string;
  Symbol            : array of byte;
  SymbolKompression : string[15];
  SymbolDehnung     : string[15];
  Talbot            : array of boolean;
  T0                : array of word;
  T1Strich          : array of real;
  T2Strich          : array of real;
  T3Strich          : array of real;
  T4Strich          : array of real;
  T5Strich          : array of real;
  T6Strich          : array of real;
  T7Strich          : array of real;
  T8Strich          : array of real;
  T9Strich          : array of real;
  TheorFarbe        : TColor;
  Ts                : array[0..30] of string;
  UmfangFarbe       : TColor;
  UnSlipLine        : TColor;
  UTischS           : string;
  Vergenz           : array of shortint;
  Vertikal          : word;
  VertrauFarbe      : TColor;
  VielfacheS        : string[12];
  Vielfach          : real;
  Winkel            : byte;
  WinkelFeld        : array of word;
  X1Fou, Y1Fou      : array of word;
  X2Fou, Y2Fou      : array of word;
  X3Fou, Y3Fou      : array of word;
  XAnfang           : real;
  XKoord            : real;
  XMitte            : word;
  Xver1Feld         : array of real;
  Xver2Feld         : array of real;
  YAnfang           : real;
  YKoord            : real;
  YMitte            : word;
  Yver1Feld         : array of real;
  Yver2Feld         : array of real;
  ZahlGlob          : word;
  Zaehler           : word;
  ZeilenS           : string;
  Zylindrizitaet    : array of byte;

implementation
end.
